<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>off_grid.NetworkingLibrary</AssemblyName>
    <Product>NetworkingLibrary</Product>
    <Version>1.0.7</Version>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <RootNamespace>NetworkingLibrary</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>PEAKNetworkingLibrary</PackageId>
    <Company>DAaCollective</Company>
    <Description>Networking library for mods using Steam instead of PUN.</Description>
    <PackageLicenseExpression>LGPL-3.0-or-later</PackageLicenseExpression>
    <PackageTags>BepInEx;Networking;Library</PackageTags>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>
</Project>
