<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>AeralisFoundation.NetworkingLibrary</AssemblyName>
    <Product>NetworkingLibrary</Product>
    <Version>1.0.9</Version>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <RootNamespace>NetworkingLibrary</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>PEAKNetworkingLibrary</PackageId>
    <Company>AeralisFoundation</Company>
    <Description>Networking library for mods using Steam instead of PUN.</Description>
    <PackageLicenseExpression>LGPL-3.0-or-later</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>PEAK;BepInEx;Networking;Library</PackageTags>
    <GeneratePackageOnBuild Condition="'$(Configuration)' == 'Release' And '$(ThunderstorePackable)' != 'false'">true</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Tests\**\*.cs" />
    <None Include="README.md" Pack="true" PackagePath="\" />
    <None Include="LICENSE.md" Pack="true" PackagePath="\" />
    <None Include="COPYING.LGPLv3" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
